# Generated by Django 4.1.1 on 2022-09-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TattooApp', '0002_tattoos_nombre_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tattoos',
            old_name='id_historia',
            new_name='id_tattoo',
        ),
    ]
