# Generated by Django 4.1.1 on 2022-09-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TattooApp', '0003_rename_id_historia_tattoos_id_tattoo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='fechadenacimiento',
        ),
    ]
