# Generated by Django 4.1.1 on 2022-09-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TattooApp', '0004_remove_artista_fechadenacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tattoos',
            old_name='id_tattoo',
            new_name='id',
        ),
    ]
